Disallow underscores in post names

diff --git a/.github/workflows/check-archive-stubs.yml b/.github/workflows/check-archive-stubs.yml
--- a/.github/workflows/check-archive-stubs.yml
+++ b/.github/workflows/check-archive-stubs.yml
@@ -46,5 +46,14 @@ jobs:
                 exit 1
             fi
 
+      - name: Check for tag files
+        run: |
+            # Disallow underscores in post names, apparently bad for SEO
+            if find ./_posts -maxdepth 1 -type f -name "*_*" | grep -q .; then
+                echo "ERROR: Files with underscores found in $DIR"
+                find "$DIR" -maxdepth 1 -type f -name "*_*"
+                exit 1
+            fi
+
 
 
